### PR TITLE
Add support for cuid2s

### PR DESCRIPTION
**Pull request by samualtnorman**
See #122.

### CODE REVIEW

**Comment by fabian-hiller** [comment]
I would prefer if we could avoid `{ checkLength: false }` altogether. I will probably work on this PR next week, as I am currently still busy with my bachelor thesis.

**Comment by samualtnorman** [comment]
What are you thinking of doing instead?

**Comment by fabian-hiller** [comment]
Maybe we should start without validating the length at all, since this can be done additionally with `length`, `minLength` and `maxLength` as you described. Then we wait if people create issues with questions or problems.

**Comment by samualtnorman** [comment]
Is this what you're looking for?

**Comment by fabian-hiller** [comment]
Yes seems to look good. I'll check your code in the next few days. Thanks a lot!

**Comment by samualtnorman** [comment]
np

**Comment by fabian-hiller** [comment]
I have your docs cached locally. I want to work out a consistent format first before we fill the API reference with content.

**Comment by fabian-hiller** [comment]
v0.14.0 is now available.

**Pull request merged**
