### PR TITLE
Make Prettify Type in Valibot Overridable for Better Developer Control

### PR DESCRIPTION
**Pull request by devcaeg**
#728

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thanks for the implementation! Should we call it `valibot` instead of `valibot/types`? Are there any downsides to this change? I need to do some research on my own before merging.

**Comment by colinhacks** [comment]
Are you sure you're able to override `type` declarations in this way? In my experiments I get a "Duplicate identifier" error.

**Comment by devcaeg** [comment]
> Thanks for the implementation! Should we call it `valibot` instead of `valibot/types`? Are there any downsides to this change? I need to do some research on my own before merging.

In reality there should be no difference.

**Comment by devcaeg** [comment]
> Are you sure you're able to override `type` declarations in this way? In my experiments I get a "Duplicate identifier" error.

I use this method on several projects and it works well. I do the override in `.d.ts` files.

**Comment by devcaeg** [comment]
For example, the `adonisjs` framework uses this method.

https://docs.adonisjs.com/guides/digging-deeper/emitter#making-events-type-safe

**Comment by fabian-hiller** [comment]
Thanks for the info and the link. I will try to review it next week.

**Comment by fabian-hiller** [comment]
> For example, the `adonisjs` framework uses this method.

Do they also use a `*.d.ts` file internally that can be overwritten by a custom `*.d.ts` file?

**Pull request closed without merging**
