### PR TITLE
docs: BIC validation

### PR DESCRIPTION
**Pull request by ariskemper**

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Are the IPv6 changes intended as part of this PR?

**Comment by ariskemper** [comment]
@fabian-hiller no it was commited by mistake. Working on rebasing the branch.

**Comment by ariskemper** [comment]
@fabian-hiller when do you plan to merge my PRs for the docs?

**Comment by fabian-hiller** [comment]
Next week. I am about to create a draft PR for our i18n feature. The implementation was more intensive than expected.

**Comment by fabian-hiller** [comment]
Thank you!

**Pull request merged**
