### PR TITLE
feat: add flag --no-isolate to improve performance

### PR DESCRIPTION
**Pull request by ariskemper**

### CODE REVIEW

**Comment by ariskemper** [comment]
@fabian-hiller maybe we should have another script like test.dev to run it locally with --no-isolate for faster development and in the pipeline we run with vitest.

**Comment by fabian-hiller** [comment]
I will give you feedback later.

**Comment by fabian-hiller** [comment]
Is there a reason why you would run it in isolation on GitHub?

**Comment by ariskemper** [comment]
Since Valibot doesn' use global variables we could use it for Github. It would speed up our branches pipelines too.

**Comment by fabian-hiller** [comment]
Yes, it speeds the process by more than 10x. So thanks a lot for the PR.

**Pull request merged**
