### PR TITLE
feat: EAN validation

### PR DESCRIPTION
**Pull request by ariskemper**

### CODE REVIEW

**Comment by ariskemper** [comment]
@fabian-hiller should i add docs to open validation PRs and we merge it after?

**Comment by fabian-hiller** [comment]
Yes, please add the docs to the PRs. Especially when we reach v1, it is important that each PR updates the docs as well, so that everything is properly documented.

**Comment by fabian-hiller** [comment]
Unfortunately, due to our rewrite a few months ago, this PR is no longer up to date with our source code. I still plan to add this action, but other things have a higher priority for me at the moment. If you or anyone else in the community is interested in creating a new PR, that would be great.

**Comment by fabian-hiller** [comment]
I will close this PR. However, I will keep it in mind when adding this action in the future.

**Pull request closed without merging**
