### PR TITLE
Type optimization to solve "type instantiation is excessively deep" error

### PR DESCRIPTION
**Pull request by romeerez**
Hello, I was experiencing some issues with TS checker, so made this PR to solve them.

For the most part, it's changing `interface` to `type`, because `interface X extends Y { ... }` is more efficient than `type X = Y & { 
... }`.

The first commit [Change BaseSchema types to interfaces](https://github.com/fabian-hiller/valibot/commit/3b2c11acad4b038b0619f22c4350823a5d229755) was already enough to fix "type instantiation is excessively deep" for my use-case.

Commits [Change BaseTransformation types to interfaces](https://github.com/fabian-hiller/valibot/commit/a09e3140f8aa07e9d9904ba809e0aeeb5af48079) and [Convert all interfaceable types to interfaces](https://github.com/fabian-hiller/valibot/commit/520a95f18fc58245e6e6f5408eaabdade6730270) also converts interfaces to types.

[Optimize partial record types](https://github.com/fabian-hiller/valibot/commit/e3c96a69854e64900b2adc41592b50b060aa1eaf): `Partial<Record<...>>` performs 2 object mappings, whereas `{ [K in X]?: X[K] }` does the same thing and performs a single mapping.

[Optimize flatten](https://github.com/fabian-hiller/valibot/commit/50e7b60b09bffa4869138274e68f7ab565adc81b):
- `ObjectPath<TEntries> | DotPath<string, TRest>` resolves to a `string` because `DotPath<string, TRest>` resolves to a `${string}` which resolves to a `string`, so I replaced it with just `string`.
- Smaller types like `{ item: infer TItem extends BaseSchema | BaseSchemaAsync }` are more efficient for TS than full types like `ArraySchema<infer TItem extends BaseSchema>`.
- Combined Map and Record branches as it was possible to combine them.

"Optimize flatten" has the lowest effect on TS performance, so if you find the optimized version messier, let's revert this file.

[Optimize merge and object types](https://github.com/fabian-hiller/valibot/commit/6a082c0921ee7f475cc7d03b2c75733eb3f575bd):
- merge: add `MergeObjectsInner` type that recursively passes the `Result` object, it's more efficient than the current `Exclude<keyof TFirstSchema['entries'], keyof MergeObjects<TRestSchemas>>`.
- simplified object input/output types.

I was optimizing types by running `tsc --noEmit --extendedDiagnostics` inside the 'library' of the Valibot repo, and checking if `Instantiations` are improving.

Results:
- Before: instantiations 1149610, mem used 262228K, check time 2.67s
- After:    instantiations 196876, mem used 247329K, check time 2.02s

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will try to review it next week. This PR is probably similar to #259.

**Comment by romeerez** [comment]
Oh, I looked through PRs but didn't notice that! It's indeed very similar. Perhaps my PR is more optimized, but I believe the other one is good and also solves instantiation problems.

**Comment by fabian-hiller** [comment]
I will investigate both PRs and consider merging the benefits of both.

**Comment by romeerez** [comment]
@fabian-hiller I created a separate PR to solve the consistency problem: https://github.com/fabian-hiller/valibot/pull/465

Consistency is such a thing that is either enforced automatically by ESLint, or it isn't fully achievable, so in that PR I'm adding an ESLint rule for that. New contributors are free to write types or interfaces, as they got used to, and ESLint will automatically convert interfaces to types when appropriate.

**Comment by romeerez** [comment]
@fabian-hiller the similar PR from November [has a comment with a nice summary](https://github.com/fabian-hiller/valibot/pull/259#issuecomment-1839986062) of `interface` advantages.

**Comment by fabian-hiller** [comment]
I will try to get back to you next week.

**Comment by fabian-hiller** [comment]
Thank your for the research and work you put into this PR. I think that I will merge #259 and this PR in the next days and therefore switch to `interface`.

**Comment by fabian-hiller** [comment]
I plan to merge this PR as it is tonight and release a new version later.

**Comment by fabian-hiller** [comment]
v0.30.0 is available

**Comment by romeerez** [comment]
Thank you for the amazing job you're doing, respect you for being so active in maintaining!

I was AFK on vacation before so wasn't responding, glad to see you have figured out all conflicts and merged this.

**Pull request merged**
