### PR TITLE
docs: :memo: added installation instructions

### PR DESCRIPTION
**Pull request by Mozart409**
For easier installation, just copy one of the installation commands

### CODE REVIEW

**Comment by fabian-hiller** [comment]
For this we have the installation guide: https://valibot.dev/guides/installation/

**Comment by Mozart409** [comment]
I understand, but I 99% of the time only visit the GitHub page. I've installed your fantastic library multiple times and every time I missed having an “installation” section, where I can easily copy and paste the installation command. Furthermore, I don't think it pollutes the README and adds more value.

**Comment by fabian-hiller** [comment]
Thank you for your feedback. I will think about it.

**Comment by Mozart409** [comment]
Hi, 
friendly reminder, it's been two months, have you decided?

Have a nice day

**Comment by fabian-hiller** [comment]
I don't want to add it at this time. However, I am happy to leave this PR open for the time being to give other developers the opportunity to provide feedback. Currently, my focus is on the library code. As soon as we get closer to v1, I will mainly focus on the documentation and rethink this again.

**Comment by fabian-hiller** [comment]
Since there are many ways to install Valibot using different package managers and registries, I don't want to add installation instructions to our readme. However, I would like to thank you for your contribution.

**Pull request closed without merging**
