### PR TITLE
Add a simple customPartial implementation

### PR DESCRIPTION
**Pull request by Demivan**
Related #76

This is an extremely simplified implementation of the proposed “partial pipe” solution.

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for the draft!

**Comment by fabian-hiller** [comment]
Do you have any alternative name ideas for `customPartial`. Will it only work or make sense in the pipe of `object`?

**Comment by fabian-hiller** [comment]
Beside PR #211, I would like to focus on a solution to this problem in the next week. It will also be important to be able to specify the path where the error message should be applied.

**Comment by Demivan** [comment]
> Do you have any alternative name ideas for `customPartial`. Will it only work or make sense in the pipe of `object`?

Maybe something like `whenValidated` or `whenFieldsValid`. 
It only makes sense with `object` pipe. So would be nice to have type system prevent usage with other validations.

**Comment by fabian-hiller** [comment]
I have added a `partialCheck` action and think that we can close this PR. Here is a code example:

```ts
import * as v from 'valibot';

const RegisterSchema = v.pipe(
  v.object({
    email: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your email.'),
      v.email('The email address is badly formatted.'),
    ),
    password1: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your password.'),
      v.minLength(8, 'Your password must have 8 characters or more.'),
    ),
    password2: v.string(),
  }),
  v.forward(
    v.partialCheck(
      [['password1'], ['password2']],
      (input) => input.password1 === input.password2,
      'The two passwords do not match.',
    ),
    ['password2'],
  ),
);
```

**Pull request closed without merging**
