### PR TITLE
feat(i18n): added Arabic translations

### PR DESCRIPTION
**Pull request by AhmedMuhsingez**
Added Arabic translations for @valibot/i18n

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

**Comment by AhmedMuhsingez** [comment]
Of course. Not a problem!

I can suggest my friend @darkrideroffate to take a look if he's available since he's also a native speaker

**Comment by fabian-hiller** [comment]
Thank you so much!

**Comment by naourass** [comment]
Native Arabic speaker here. I reviewed the Arabic translations and they are all correct. Clear and relavant vocabulary was used with no grammar or other mistakes.

**Comment by AhmedMuhsingez** [comment]
@DARKRIDEROFFATE 👀👀👀

**Comment by fabian-hiller** [comment]
Thank you! I plan to merge this PR in the next days.

**Pull request merged**
