### PR TITLE
Primitives values in literal schema

### PR DESCRIPTION
**Pull request by fvckDesa**
This PR add all primitives values on literal schema.

Solve Issue #97

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Great! Thanks a lot! I'll check your code as soon as I find time and publish this improvement with the next version.

**Review by kassiomaia — APPROVED** [review]

**Review by kassiomaia — APPROVED** [review]
I just do not sure if null should be a primitive considering that null extends from object!

**Comment by fabian-hiller** [comment]
I think `null` and `undefined` should be removed because a literal with this datatype makes no sense. This would also have the consequence that the type `Primitive` should be renamed to `Literal`. The tests would then have to be updated. Other than that, the code looks good.

**Comment by fvckDesa** [comment]
I have take the primitives data types from [MDN Documentation](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) that includes null and undefined between primitives values.
I think that null and undefined is not very usefull as literal value, but I don't see why someone shouldn't have the possibility to use them

**Comment by fabian-hiller** [comment]
Since this does not change the schema's implementation, it is not so important to me whether we include `null` and `undefined`. Both have their advantages and disadvantages. If we leave it like it is, `literal` is more flexible to use on the one hand. However, the API of Valibot becomes more confusing, on the other hand, as there are now two ways to achieve the same thing. Also, strictly speaking, there is no `null` and `undefined` literal since these datatypes cannot be further specified.

Feel free to give me feedback on this again. I'll probably decide tomorrow how I want to proceed.

**Pull request merged**
