### PR TITLE
feat: ISIN validation

### PR DESCRIPTION
**Pull request by ariskemper**
- Validation for ISIN ( Internatinal Securities Identification Number ) with format validation and use of luhn algorithm

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you so much for all the work you put into Valibot! It means a lot to me and it provides a great value to all Valibot users. If you have time during the winter break, I would love to get to know you in a video call.

**Comment by ariskemper** [comment]
Sure we could have a call and discuss how we could improve the library.

**Comment by fabian-hiller** [comment]
In case you use Discord, feel free to send me (fabianhiller) a friend request.

**Comment by fabian-hiller** [comment]
Can you check your code against the [formatting requirements](https://www.isin.org/isin-format/) and this [code](https://github.com/validatorjs/validator.js/blob/master/src/lib/isISIN.js) of [validator.js](https://github.com/validatorjs/validator.js) to see if it covers every case?

**Comment by ariskemper** [comment]
@fabian-hiller i refactor and moved isISIN to validation. My tests covers even more test cases then validator.js so it should be fine. Ready to be merged.

**Comment by fabian-hiller** [comment]
Thanks! Will have a look at it next week.

**Comment by fabian-hiller** [comment]
Unfortunately, due to our rewrite a few months ago, this PR is no longer up to date with our source code. I still plan to add this action, but other things have a higher priority for me at the moment. If you or anyone else in the community is interested in creating a new PR, that would be great.

**Comment by fabian-hiller** [comment]
I will close this PR. However, I will keep it in mind when adding this action in the future.

**Pull request closed without merging**
