### PR TITLE
Add brand type

### PR DESCRIPTION
**Pull request by mrsekut**
## Introduction

This PR introduces the concept of "branded types" to the `valibot` library, a feature inspired by the [`.brand` in `zod`](https://github.com/colinhacks/zod#brand).

## Motivation

TypeScript is structurally typed, which means it doesn't distinguish between types with the same structure. This can be problematic in scenarios where we want to differentiate between types that have the same underlying structure but represent different concepts.

For instance, consider a project where we're working with multiple units of length, like millimeters (mm) and centimeters (cm). Both would typically be represented as `number` in TypeScript. However, with the introduction of branded types, we can now differentiate between them:

```typescript
const MM = brand(number(), 'MM');
const CM = brand(number(), 'CM');
```

## Implementation Details

While designing the interface for this feature, I considered an approach like `brand<'MM'>(number())`. However, due to TypeScript's nature, when there are multiple generic type arguments, we can't specify just one. Hence, the current implementation was chosen. This is an area where I believe there's room for discussion, especially considering usability.

It's important to note that the `brand` function doesn't alter the value in any way. Therefore, the result of the `parse` function remains unchanged before and after using `brand`. Consequently, the test cases added in this PR focus on type-level checks.

## On the Naming: "brand"

The term "brand" seems to be frequently used within the TypeScript community. In fact, it even appears in TypeScript's own codebase. You can find a reference to it [here](https://github.com/Microsoft/TypeScript/blob/7b48a182c05ea4dea81bab73ecbbe9e013a79e99/src/compiler/types.ts#L693-L698).

While there are similar terms like "opaque" that could be used, aligning with `zod` and using "brand" seems appropriate and consistent.

## Personal Note

I've been using `zod` in my projects and heavily relied on the `brand` feature. I felt the need for this feature in `valibot` as I'm transitioning to it.

### CODE REVIEW

**Comment by fabian-hiller** [comment]
I think that `brand` is a method and not a schema or? Can you move it to the methods? This PR fixes #56.

**Comment by mrsekut** [comment]
Thank you for the feedback.

I understood your point and have moved `brand` to the `methods/` directory as suggested.

I've added the changes in a subsequent commit. If there were any issues, please feel free to squash the commits during the merge. If necessary, I could also rebase and force push the changes.

**Comment by fabian-hiller** [comment]
Thank you! I will check and merge your code tonight or in the coming days.

**Comment by fabian-hiller** [comment]
I am about to release a new version that will include the `brand` method. Let me know then if it works in practice for you as expected. Thanks for your contribution!

**Pull request merged**
