### PR TITLE
refactor: flatten

### PR DESCRIPTION
**Pull request by ariskemper**

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thanks for improving the code. I think I don't like to split small functions into even smaller ones when it's not necessary. It increases the bundle size and makes the code more complex in my eyes.

**Comment by ariskemper** [comment]
@fabian-hiller would be good to know how much this change affects the size?

**Comment by fabian-hiller** [comment]
Thank you for the research. I think readability is subjective here and I prefer not to split up small functions unnecessarily.

**Comment by fabian-hiller** [comment]
Since we rewrote this function is the previous rewrite, I will close this PR.

**Pull request closed without merging**
