### PR TITLE
Add `*graphemes` validation actions.

### PR DESCRIPTION
**Pull request by remonke**

### CODE REVIEW

**Comment by 2-NOW** [comment]
Closes: #784

**Comment by fabian-hiller** [comment]
Thank you! I will try to review and merge this PR this or next week.

**Comment by fabian-hiller** [comment]
I started to work on this PR and will probably merge it tomorrow 🙌

**Comment by fabian-hiller** [comment]
I also started to implement the words actions.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.1 with the grapheme actions is available

**Comment by nikeee** [comment]
I hate to be _that_ guy but the naming might not be correct. A grapheme can be something like the dots over an ö. Composite characters like ö[^1] or emojis are actually grapheme **clusters** (something that is perceived as a single character by the user).

Also note that what counts as a grapheme cluster is dependent on the device + locale settings where the code runs and that it can change over time. 
For example, some browsers might render 🐱‍👤 as a single grapheme cluster (Edge on Windows 10+) but as two different grapheme clusters on other systems[^2] (like the device I'm typing this on). This may yield unexpected behavior due to different definitions of grapheme clusters on participating systems.

[^1]: In that case, dependent on the used Unicode normalization.
[^2]: See: https://emojipedia.org/ninja-cat

**Comment by fabian-hiller** [comment]
Thanks for your feedback. I couldn't find a case where the locale actually made a difference, but I'm happy to improve the implementation if people actually run into problems.

**Pull request merged**
