### PR TITLE
feat: add vietnam language

### PR DESCRIPTION
**Pull request by thinhbg2812-2**
Add Vietnamese for @valibot/i18n

Here my brother: @hongky-1994

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Will @hongky-1994 review your translations?

**Review by hongky-1994 — CHANGES_REQUESTED** [review]
I think some changes should be made to improve understanding of error messages.

**Comment by fabian-hiller** [comment]
Is this ready to be merged, or should another native speaker do a final review?

**Comment by thinhbg2812-2** [comment]
I think it's ready; i asked him pretty much about the naming and context, and he has high credit in team xD

**Comment by fabian-hiller** [comment]
Ok. Thank you! I will review and merge it later this month.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.2 of our i18n package is available

**Pull request merged**
