### PR TITLE
docs(website): migrate main concepts away from first-person

### PR DESCRIPTION
**Pull request by BastiDood**
In line with #687, I have begun work towards the migration of the documentation from first-person to a more neutral tone. I was personally amused by the personality at first, but as suggested by many others, it did get old pretty quick.

This PR only adjusts the text for the Main Concepts section of the Guides page. There is a lot more work to do, but I'd like to keep this PR well-scoped in the meantime. Let me know if you have any concerns regarding the updated version of the text.

> [!NOTE]
> As an aside, I'd like to invite you in accepting this PR as a valid submission for this year's [Hacktoberfest](https://hacktoberfest.com/). There are [two ways](https://hacktoberfest.com/participation/) to do this: (1) add the `hacktoberfest` topic to the repository or (2) add the `hacktoberfest-accepted` label only to this PR if the previous option is not preferable. Thanks! 🚀

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you! Please keep to first-person style in the introduction guide. I will have another look at this PR tomorrow.

**Comment by BastiDood** [comment]
> Please keep to first-person style in the introduction guide.

Yes, the entire Get Started section (which contains the Introduction guide) is untouched. This PR only edits the Main Concepts section: mental model, schemas, pipelines, parse data, infer types, methods, and issues.

**Comment by fabian-hiller** [comment]
I have added the label and topic for Hacktoberfest 🚀

**Comment by BastiDood** [comment]
Thanks! Looking forward to seeing this merged. 🙇

**Pull request merged**
