### PR TITLE
[WIP] docs: add playground page

### PR DESCRIPTION
**Pull request by kazizi55**
Implements: https://github.com/fabian-hiller/valibot/issues/245#issuecomment-1793778012

### CODE REVIEW

**Comment by kazizi55** [comment]
badge
Remaining tasks:
- [ ] fix build error
- [ ] adjust CSS
- [ ] implement convert logic from Zod to Valibot

**Comment by kazizi55** [comment]
@fabian-hiller 
So sorry for my late reply 🙏  🙏  

>  I think a Zod to Valibot translation would be cool as well as a general TypeScript Playground to try out Valibot schemas.

Yes, I agree with you! 😄 
I'm gonna open this PR in the next few days.

**Comment by fabian-hiller** [comment]
Thank you very much! My focus is currently on other parts of the project until we get more close to v1 but maybe the [code](https://github.com/lxsmnsyc/seroval-playground) from this [website](https://seroval.vercel.app/) is worth a look when implementing our playground.

**Comment by kazizi55** [comment]
@fabian-hiller 
> maybe the [code](https://github.com/lxsmnsyc/seroval-playground) from this [website](https://seroval.vercel.app/) is worth a look when implementing our playground.

Thank you! I'm gonna take a look at the code and the playground🙏

**Pull request closed without merging**
