### PR TITLE
feat(i18n) Add Italian Language

### PR DESCRIPTION
**Pull request by kristian-marku**
Added Italian translations for @valibot/i18n

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

**Comment by kristian-marku** [comment]
> Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

I think there are many Italians here ,I don't have many acquaintances who could do this, maybe one. I'll try asking him.
They are quite simple sentences, you can also check them with google.

**Comment by Ookamini95** [comment]
Another italian developer to the rescue, i can vouch for the translations, they look good enough imo.

**Comment by fabian-hiller** [comment]
Thank you! I will review and merge it soon.

**Pull request merged**
