### PR TITLE
add more valid/invalid cases in `ipv4` action's tests

### PR DESCRIPTION
**Pull request by EltonLobo07**

### CODE REVIEW

**Comment by EltonLobo07** [comment]
Do you think I have covered the majority of the cases? If not, can you help me understand what you mean by `cover all possible scenarios based on the regex used`?

**Comment by fabian-hiller** [comment]
This is our IP v4 regex:

```ts
/^(?:(?:[1-9]|1\d|2[0-4])?\d|25[0-5])(?:\.(?:(?:[1-9]|1\d|2[0-4])?\d|25[0-5])){3}$/u
```

The idea is basically to test the entire regex definition, so if we accidentally change the regex in the future, our tests should fail and warn us.

**Comment by fabian-hiller** [comment]
Thank you very much! I am busy this weekend, but I will try to review it next week.

**Comment by EltonLobo07** [comment]
I think I can improve the added test cases. I'll let you know once I am done (probably tomorrow) so that you can review the changes then.

**Comment by EltonLobo07** [comment]
Updated. Feel free to review the PR.

**Pull request merged**
