### PR TITLE
Add Arabic to i18n

### PR DESCRIPTION
**Pull request by aashahin**

### CODE REVIEW

**Comment by fabian-hiller** [comment]
I am sorry. This seems to be a duplicate of #527. Perhaps you can review #527 to make it perfect.

**Comment by aashahin** [comment]
Sorry, i didn't notice that

**Comment by fabian-hiller** [comment]
Don't worry about it! I am happy about your contribution. Any chance you could check and improve the translations of #527?

**Comment by aashahin** [comment]
I checked it, No grammatical errors

**Comment by fabian-hiller** [comment]
Thanks for your review! I checked both PRs with diffchecker.com and found many differences. How do you suggest I proceed?

**Comment by aashahin** [comment]
I have reviewed the differences and only see differences in the translation. The keys and values are all as they should be, so I don't see any issues with that translation. You can accept it.

**Pull request closed without merging**
