### PR TITLE
Feature: Norwegian translation (nb-NO)

### PR DESCRIPTION
**Pull request by sifferhans**

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

**Comment by sifferhans** [comment]
@fabian-hiller Sure, I can tag them here if you want 😊

**Comment by fabian-hiller** [comment]
Yes, please do. Thank you!

**Comment by fabian-hiller** [comment]
@sifferhans don't forget to tag them.

**Comment by sifferhans** [comment]
@fredrikved Could you take a look at the translations in this PR when/if you have the time?:)

**Comment by fredrikved** [comment]
> @fredrikved Could you take a look at the translations in this PR when/if you have the time?:)

Looks good to me.

**Comment by fabian-hiller** [comment]
Can you explain why the ISO code `nb` is not sufficient? Why did you choose `nb-NO` instead?

**Comment by sifferhans** [comment]
@fabian-hiller Ah, my bad. `nb` should indeed be sufficient 👍🏼 I'll update the PR

**Comment by fabian-hiller** [comment]
Thank you! Can you explain the difference between the [ISO codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) `no`, `nb` and `nn`? Why is `nb` the correct ISO code for the translations provided?

**Comment by sifferhans** [comment]
@fabian-hiller We have two different written languages in Norway, because of historical reasons!

- **N**orweigan **B**okmål - _"book language"_ in english - is based on danish, as Norway was under Denmark for around 400 years or so.
- **N**orwegian **N**ynorsk - _"new norwegian"_ in english - was created after Norway became independent in the early 1800s, and is based on many of the spoken dialects from around the country.

That's the tldr of it.

So `nb` is "Norwegian Bokmål", `nn` is "Norwegian Nynorsk" and `no` is usually "Norwegian Bokmål" as well, as that is more used.

**Comment by fabian-hiller** [comment]
To summarize, `nb` is the write code for your translations?

**Comment by sifferhans** [comment]
@fabian-hiller Correct 👍🏼

**Comment by fabian-hiller** [comment]
v0.7.0 is available

**Pull request merged**
