### PR TITLE
Allow additional properties in object schema and allow to block those additional properties via the strict method

### PR DESCRIPTION
**Pull request by FabienDehopre**
This PR implements the feature request #143

### CODE REVIEW

**Comment by fabian-hiller** [comment]
This seams related to https://github.com/fabian-hiller/valibot/pull/15

Since this this a modular library and current most users expect the current behaviour, I prefer to implement a method instead of changing the `object` schema. I am happy to receive feedback on this.

**Comment by FabienDehopre** [comment]
Indeed. I didn't spot that PR (and related issue/discussion #17).
I understand your point.
Here what I propose instead: Leave the default behavior of the object schema parser as it is actually but add a new `extraEntries` array property to the `_parser` result that can be validated by the `strict` method.
Additionally, I would also create 2 new "methods" for the object schema:
- `strip` (or any other name that you see fit): ignores the additional properties given in the input (so no additional properties in the output).
- `passthrough` (or any othe name that you see fit): copies the additional properties from input to the output as-is.

And update the `strict` method to throw an error if the `extraEntries` array isn't empty (more or less the same behavior as now).

What do you think about this proposition?

**Comment by fabian-hiller** [comment]
Thanks for your feedback on this. I will probably have more time for open source again next week and will answer you then in detail.

**Comment by fabian-hiller** [comment]
I added `passthrough` and `strip` in v0.14.0. Thank you for your contribution!

**Pull request closed without merging**
