### PR TITLE
Change error massage param to function

### PR DESCRIPTION
**Pull request by vicimpa**
For multi language. Example:
```ts
const LoginSchema = object({
  email: string([
    minLength(1, () => 'Please enter your email.'),
    email(() => 'The email address is badly formatted.'),
  ]),
  password: string([
    minLength(1, () => 'Please enter your password.'),
    minLength(8, () => 'Your password must have 8 characters or more.'),
  ]),
});
```

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you very much! Do you have an opinion on this issue? https://github.com/fabian-hiller/valibot/issues/36

**Comment by vicimpa** [comment]
Yes, sure. See.
```js
const LoginSchema = object({
  email: string([
    minLength(1, () => i18n["min_length"]),
    email(() => i18n["email_fail"]),
  ])
});
```

**Comment by ragokan** [comment]
Just wanted to comment, that looks pretty good for localization.

**Comment by fabian-hiller** [comment]
I haven't made a decision about i18n yet. If you have a clear opinion, feel free to tell more about why this solution is better than the other ones in #36.

**Comment by vicimpa** [comment]
My solution is more universal and is not tied to the i18n library

**Comment by thundermiracle** [comment]
Is there anyone who agrees that passing messages or functions to every validation function is inconvenient as I do?

**Comment by fabian-hiller** [comment]
@thundermiracle are you interested in a global solution to pass individual error messages?

**Comment by thundermiracle** [comment]
> @thundermiracle are you interested in a global solution to pass individual error messages?

Yes, of course. What's the solution?

**Comment by fabian-hiller** [comment]
There are several ideas in issue #36. Which one do you prefer?

**Comment by thundermiracle** [comment]
> There are several ideas in issue #36. Which one do you prefer?

I'm not sure. But 
1. Passing functions or messages to every function is not preferable
2. Adding global state as gmaxlev suggested is not that good in functional programming

What about record map which support both string and function which others suggested?

Maybe we should discuss it in #36 ?

**Comment by fabian-hiller** [comment]
Yes, please share your ideas and feedback there. I plan to work on an implementation next week.

**Comment by fabian-hiller** [comment]
Thanks again for creating this PR. Since I would do some basic things differently and it was faster for me to implement them directly, I made the changes independently. However, I have added you as a co-author and linked the PR in the changelog.

**Pull request closed without merging**
