### PR TITLE
feat: support metadata

### PR DESCRIPTION
**Pull request by xcfox**
Implements https://github.com/fabian-hiller/valibot/issues/373 

- All schema functions accept the metadata argument:
  - Most schemas accept this argument using the location of the `message`.
  - Additional metadata argument added for some special schemas. `any()`, `unknown()`, `recursive()`
- The metadata argument has been added to the following method:

  - `merge()`
  - `omit()`
  - `partial()`
  - `pick()`
  - `required()`

- Use `isSchema` in `restAndDefaultArgs` to distinguish whether an object is a valid schema or metadata.

- Currently only the `description` field has been added to the metadata.
  We can either follow the [json-schema](https://json-schema.org/understanding-json-schema/reference/generic) completely, or not pre-populate any fields like [yup](https://github.com/jquense/yup?tab=readme-ov-file#schemametametadata-schemametadata-schema), or just a built-in `description` field like [zod](https://zod.dev/?id=describe).

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for creating this PR. I will review it in the next weeks.

**Comment by xcfox** [comment]
@fabian-hiller Thank you! 

I think metadata is an essential feature, and both [yup](https://github.com/jquense/yup?tab=readme-ov-file#schemametametadata-schemametadata-schema) and [zod](https://zod.dev/?id=describe) support it.

Do you think metadata needs to be discussed in more depth in terms of implementation? Do we need to consider the placement of metadata settings or the built-in metadata field?

**Comment by fabian-hiller** [comment]
I am currently focused on other stuff. I will get back to you on the weekend or next week.

**Comment by jeremyjacob** [comment]
Metadata would be super nice for exporting schemas to other formats like OpenAPI.

**Comment by fabian-hiller** [comment]
Can you make an example with dummy code?

**Comment by vova-white** [comment]
> Metadata would be super nice for exporting schemas to other formats like OpenAPI.
> Can you make an example with dummy code?

Maybe something like:

```js
const ProductSchema = pipe(
  object({
    productId: pipe(
      number(),
      integer(),
      minValue(1),
      withDescription("The unique identifier for a product"),
    ),
    productName: pipe(
      string(),
      nonEmpty(),
      withDescription("Name of the product"),
    ),
  }),
  withDescription("A product from Acme's catalog"),
);
```

Will be converted to: 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "ProductSchema",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "productName": {
      "description": "Name of the product",
      "type": "string"
    }
  }
}
```

I think this will be very useful for those who develop a public API and use, for example, [valibot-json-schema](https://github.com/gcornut/valibot-json-schema) to generate documentation.

**Pull request closed without merging**
