### PR TITLE
Add getDefault method 

### LINKED ISSUE #105: Add a way of getting default values from a schema
It is really useful to populate fields in a form.

Example of this method in `Yup` https://github.com/jquense/yup#schemagetdefaultoptions-object-any

### PR DESCRIPTION
**Pull request by Demivan**
Closes #105

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for your contribution! I think that it is not necessary to implement a function for this, since the default value can be made directly accessible or not?

**Comment by Demivan** [comment]
I have made it the same as in `Yup`. `Yup` actually clones defaults if it is an object or an array, I think `Valibot` should clone it too, in case it is mutated.

https://github.com/jquense/yup#schemadefaultvalue-any-schema

Function default are also useful for defaults that change over time (`new Date`).

**Comment by fabian-hiller** [comment]
With #96 there is another issue. I think we need to add a separate type definition for each schema, like I did for `transform` and `brand`. In this definition we could then add the key `default` to make the default value accessible there.

**Comment by fabian-hiller** [comment]
> Function default are also useful for defaults that change over time (new Date).

When a date is created, it has a fixed value or doesn't it?

**Comment by Demivan** [comment]
> When a date is created, it has a fixed value or doesn't it?

`new Date()` returns current date and time.

Function defaults are useful for nested schemas too.

```ts
const userSchema = object({ name: withDefault(string(), 'John Doe') })

// Populate default users array with one default user
const usersSchema = withDefault(array(userSchema), () => [getDefault(userSchema)])
```

**Comment by Demivan** [comment]
> With https://github.com/fabian-hiller/valibot/issues/96 there is another issue. I think we need to add a separate type definition for each schema, like I did for transform and brand. In this definition we could then add the key default to make the default value accessible there.

I don't think it needs a definition for each schema. It would actually be the same signature as with `optional` method.
I like idea by @ooga https://github.com/fabian-hiller/valibot/issues/96#issuecomment-1678715229. Passing a default value (or a function to get one) to `optional` method would make schema definition simpler, and `withDefault` method can be removed. @fabian-hiller, what do you think?

**Comment by fabian-hiller** [comment]
Yes, I think the idea of `optional` is not bad. However, I currently have to focus on my bachelor's thesis, and I do not want to make this decision quickly.

If we also allow a function for the default value with `optional` or `withDefault`, we could return the value with a setter. That way, it can still be accessed with `.default`.

**Comment by Demivan** [comment]
> I currently have to focus on my bachelor's thesis, and I do not want to make this decision quickly.

No pressure :) This can wait.

> This is only true if instead of `new Date()` a function `() => new Date()` is passed and this is currently not supported by Valibot.

I have added support for this in this PR. Using a function to return a default value is useful when the default value depends on some external state too. 

> And in the code example, I would write the following:
```ts
const userSchema = object({ name: withDefault(string(), 'John Doe') })

// Populate default users array with one default user
const usersSchema = withDefault(array(userSchema), [userSchema.object.name.default])
```

This would create an array with just a name `['John Doe']` and not a user object `[{ name: 'John Doe' }]`.

> If we extend `optional`, perhaps we should do the same with `nullable` and `nullish`.

I agree.

**Comment by fabian-hiller** [comment]
I deprecated `withDefault` and revised `optional`, `nullable` and `nullish`. Also, I added a `getDefault` method and added you as co-author.

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.

**Comment by Demivan** [comment]
@fabian-hiller I haven't tried 0.15 yet, but I don't see implementation of `default` getter for wrapping schemas (`object`, `recursive`) etc. Would `getDefault` work on `object` schema that has properties with `default`?
You can see implementation for `object` schema in this PR.

**Comment by fabian-hiller** [comment]
Yes I have looked at your implementation. No, that doesn't work because I think that is only needed in rare cases and therefore I don't want to add it globally to every schema. My plan was to wait to get feedback on this.

**Comment by Demivan** [comment]
What I was thinking about is using `getDefault` for getting default values for the entire form. And because form would almost always use an `object` schema, that would not work.

**Pull request closed without merging**
