### PR TITLE
feat(i18n): add Hungarian translations

### PR DESCRIPTION
**Pull request by kukac7**

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

**Comment by kukac7** [comment]
@fabian-hiller my friend liked it. 😉

**Comment by fabian-hiller** [comment]
Thanks! I plan to review and merge this PR next week.

**Comment by fabian-hiller** [comment]
Thank you!

**Pull request merged**
